# Numpy ndarray对象

- `numpy`定义了一个n维数组对象，简称`ndarray`对象，它是一个一系列`相同`类型元素组成的数组集合。数组中的每个元素都占有大小相同的内存块。
- `ndarray`对象采用了数组的`索引机制`，将数组中的每个元素映射到内存块上，并且按照一定的布局对内存块进行排列。



In [1]:
import numpy as np

# numpy创建数组

```python
numpy.array(object, dtype = None, copy = True, Order = None, subok = False, ndmin = 0)
```

参数：

| 序号 | 参数   | 描述说明                                                     |
| ---- | ------ | :----------------------------------------------------------- |
| 1    | object | 表示一个数组序列                                             |
| 2    | dtype  | 可选参数，通过它可以改变数组的数据类型                       |
| 3    | copy   | 可选，当数据源是ndarray是表示数组能否被复制，默认是True                  |
| 4    | Order  | 可选，以哪种内存布局创建数组，有3个可选值，分别是C（行序列）/F（列序列）/A（默认） |
| 5    | ndmin  | 可选，用于指定数组维数                                       |
| 6    | subok  | 可选，类型为bool，默认为False。为True时，使用object的内部数据类型；为False时，使用object数组的数据类型。 |



In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [4]:
np.array((1,2,3,4,5)) # 元组

array([1, 2, 3, 4, 5])

In [5]:
type(np.array((1,2,3,4,5)))

numpy.ndarray

In [6]:
a = np.array([1,2,3,4,5])

b = np.array(a)

b

array([1, 2, 3, 4, 5])

In [7]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.array([i**2 for i in range(10)]) # 里面是列表

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
# 创建10以内的偶数的数组
np.array([i for i in range(10) if i%2 == 0])

array([0, 2, 4, 6, 8])

In [10]:
# 第二种做法
np.array(range(0,11,2))

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.array([1,1.4,'5'])

array(['1', '1.4', '5'], dtype='<U32')

In [12]:
# 二维数组(可以嵌套，列表元组都可以)
np.array([
    [1,'b',3],
    ('1','b','3')
])

array([['1', 'b', '3'],
       ['1', 'b', '3']], dtype='<U21')

In [13]:
# 注意嵌套序列数量不一会怎么样
ar4 = np.array([[1,2,3],[1,2,3]]) 

In [14]:
ar4

array([[1, 2, 3],
       [1, 2, 3]])

In [15]:
ar4.shape

(2, 3)

 1. 设置dtype参数，默认自动识别

In [16]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [17]:
a_dtype = np.array(a, dtype = 'float')
a_dtype

array([1., 2., 3., 4., 5.])

## 思考如何将浮点型的数据，设置为整形，会是什么情况？

In [18]:
np.array([1.1,2.2,3,1.2], dtype = 'int')

array([1, 2, 3, 1])

 2.设置copy参数,默认为True

In [19]:
a = np.array([1,2,3,4,5])
b = np.array(a)

In [20]:
print('a:',id(a),'b:',id(b))

a: 4442187504 b: 4442187600


In [21]:
a = np.array([1,2,3,4,5])
# 定义b，当设置copy参数为Fasle时，不会创建副本，
# 两个变量会指向相同的内容地址，没有创建新的对象
b = np.array(a, copy=False)
# 输出a和b的id
print('a:', id(a), '  b:', id(b))
print('以上看出a和b的内存地址')
# 由于a和b指向的是相同的内存地址，因此当修改b的元素时，a会发生变化
b[0] = 10
print('a:',a,'  b:',b)

a: 4442187984   b: 4442187984
以上看出a和b的内存地址
a: [10  2  3  4  5]   b: [10  2  3  4  5]


当默认为True时，表明是独立的复制，而不是引用；
为False时，表明是引用

3. ndmin 用于指定数组的维度

In [22]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [23]:
b = np.array(a, ndmin = 2)
b

array([[1, 2, 3]])

4.subok参数，类型为bool值，默认False。为True，使用object的内部数据类型；False：使用object数组的数据类型。

In [24]:
# 创建一个矩阵
a = np.mat([1,2,3,4])
# 输出为矩阵类型
print(type(a))

#既要复制一份副本，又要保持原类型
at = np.array(a,subok=True)
af = np.array(a)  # 默认为False
print('at,subok为True:',type(at))
print('af,subok为False:',type(af))
print(id(at),id(a))


<class 'numpy.matrix'>
at,subok为True: <class 'numpy.matrix'>
af,subok为False: <class 'numpy.ndarray'>
4442264000 4442263872


In [25]:
a = np.array([1,2,3,4])
c = a.copy() # copy使用的多一点
print(id(a),id(c))

4442231984 4442189424



# arange()生成区间数组
根据 start 与 stop 指定的范围以及 step 设定的步长，生成一个 ndarray。

```python
numpy.arange(start, stop, step, dtype)
```
参数说明   

| 序号 | 参数 | 描述说明 |
| :--- | :--- | :--- |
| 1      | start| 起始值，默认为0   |
| 2   | stop | 终止值（不包含）        |
| 3      | step | 步长，默认为1        |
| 4      | dtype |  返回ndarray的数据类型，如果没有提供，则会使用输入数据的类型。     |

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(3.1)

array([0., 1., 2., 3.])

In [28]:
range(3)

range(0, 3)

In [29]:
np.arange(4,dtype = 'float')

array([0., 1., 2., 3.])

In [30]:
np.arange(10,100,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [31]:
np.arange(100000) # 只打印边边角角

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [32]:
np.arange(20,step = 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [33]:
arr = np.arange(200+1,step = 3)

In [34]:
len(arr)

67

## 如何防止 float 不精确影响numpy.arange
> <font color=red>注意：ceil((stop - start)/step)确定项目数，小浮点不精确(stop = .400000001)可以向列表中添加意外值。</font>
#### 想得到一个长度为3的、从0.1开始的、间隔为0.1的数组，想当然地如下coding，结果意料之外：

In [35]:
np.arange(0.1,0.5,0.1)

array([0.1, 0.2, 0.3, 0.4])

# linspace() 创建等差数列

返回在间隔[开始，停止]上计算的num个均匀间隔的样本。<b>数组是一个等差数列构成</b>

```python
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```

参数说明   

| 序号 | 参数 | 描述说明 |
| :--- | :--- | :--- |
| 1      | start| 必填项，序列的起始值，  |
| 2   | stop | 必填项，序列的终止值，如果endpoint为true，该值包含于数列中      |
| 3      | num | 要生成的等步长的样本数量，默认为50      |
| 4      | endpoint |  该值为 true 时，数列中包含stop值，反之不包含，默认是True。  | 
| 5      | retstep |  如果为 True 时，生成的数组中会显示步长，反之不显示。   | 
| 6      | dtype |  ndarray 的数据类型 | 

In [36]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [37]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [38]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [39]:
np.linspace(1,10,10,dtype='int')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
np.linspace(1,10,10,retstep=False)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
a = np.linspace(1,5,5)
a

array([1., 2., 3., 4., 5.])

In [42]:
a = np.linspace(1,5.1,5)
a

array([1.   , 2.025, 3.05 , 4.075, 5.1  ])

In [43]:
np.linspace(1,5,5,endpoint=False) # 不包含末尾值5

array([1. , 1.8, 2.6, 3.4, 4.2])

In [44]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [45]:
a = np.linspace(2.0,3.0,5,retstep=True) # 显示步长
a

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [46]:
type(a)

tuple

In [47]:
a = np.linspace(2.0,3.0,5,endpoint=False,retstep=True)
a

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)

#### 等差数列 在线性回归经常作为样本集
如：生成x_data，值为[0, 100]之间500个等差数列数据集合作为样本特征，根据目标线性方程y=3*x+2，生成相应的标签集合y_data

In [48]:
y_data = np.linspace(0,100,500)
y_data

array([  0.        ,   0.2004008 ,   0.4008016 ,   0.6012024 ,
         0.80160321,   1.00200401,   1.20240481,   1.40280561,
         1.60320641,   1.80360721,   2.00400802,   2.20440882,
         2.40480962,   2.60521042,   2.80561122,   3.00601202,
         3.20641283,   3.40681363,   3.60721443,   3.80761523,
         4.00801603,   4.20841683,   4.40881764,   4.60921844,
         4.80961924,   5.01002004,   5.21042084,   5.41082164,
         5.61122244,   5.81162325,   6.01202405,   6.21242485,
         6.41282565,   6.61322645,   6.81362725,   7.01402806,
         7.21442886,   7.41482966,   7.61523046,   7.81563126,
         8.01603206,   8.21643287,   8.41683367,   8.61723447,
         8.81763527,   9.01803607,   9.21843687,   9.41883768,
         9.61923848,   9.81963928,  10.02004008,  10.22044088,
        10.42084168,  10.62124248,  10.82164329,  11.02204409,
        11.22244489,  11.42284569,  11.62324649,  11.82364729,
        12.0240481 ,  12.2244489 ,  12.4248497 ,  12.62

#  等比数列

返回在间隔[开始，停止]上计算的num个均匀间隔的样本。<b>数组是一个等比数列构成</b>

```python
np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
```

参数说明   

| 序号 | 参数 | 描述说明 |
| :--- | :--- | :--- |
| 1      | start| 必填项，序列的起始值，  |
| 2   | stop | 必填项，序列的终止值，如果endpoint为true，该值包含于数列中      |
| 3      | num | 要生成的等步长的样本数量，默认为50      |
| 4      | endpoint |  该值为 true 时，数列中包含stop值，反之不包含，默认是True。  | 
| 5      | base |  对数 log 的底数   | 
| 6      | dtype |  ndarray 的数据类型 | 

In [49]:
np.logspace(0,9,10,base=2)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

np.logspace(A,B,C,base=D)
- A: 生成数组的起始值为D的A次方
- B:生成数组的结束值为D的B次方
- C:总共生成C个数
- D:指数型数组的底数为D，当省略base=D时，默认底数为10

In [50]:
np.logspace(0,2,3,base=2)

array([1., 2., 4.])

In [51]:
np.logspace(0,2,base=2)

array([1.        , 1.02869573, 1.05821491, 1.08858117, 1.1198188 ,
       1.15195282, 1.18500895, 1.21901365, 1.25399415, 1.28997843,
       1.3269953 , 1.36507441, 1.40424622, 1.44454209, 1.48599429,
       1.52863599, 1.57250132, 1.61762539, 1.66404434, 1.71179531,
       1.76091654, 1.81144733, 1.86342814, 1.91690058, 1.97190744,
       2.02849277, 2.08670186, 2.1465813 , 2.20817903, 2.27154434,
       2.33672798, 2.4037821 , 2.47276039, 2.54371806, 2.61671192,
       2.69180039, 2.76904357, 2.84850331, 2.9302432 , 3.01432868,
       3.10082705, 3.18980756, 3.28134142, 3.37550192, 3.47236443,
       3.57200647, 3.67450782, 3.77995051, 3.88841897, 4.        ])

In [52]:
# 我们先使用前3个参数，将[1,5]均匀分成3个数，得到{1,3,5}，
# 然后利用第4个参数base=2(默认是10）使用指数函数可以得到最终输出结果 {2^1,2^3,2^5}
np.logspace(1,5,3,base=2)

array([ 2.,  8., 32.])

In [53]:
np.logspace(1.0,2.0,10)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [54]:
a = np.linspace(1.0,2.0,10)
print(a)
10 ** a

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

## 练习题

一个穷人到富人那里去借钱，原以为富人不愿意，哪知富人一口答应了下来，
但提出了如下条件：
- 在30天中，富人第一天借给穷人1万元，第二天借给2万，以后每天所借的钱数都比上一天的多一万；
- 但 借钱第一天，穷人还1分钱，第二天还2分钱，以后每天所还的钱数都是上一天的两倍。
- 30天后互不相欠，

穷人听后觉得挺划算，本想定下来，但又想到富人是个吝啬出了名的，怕上当，所以很为难。


In [55]:
a = np.linspace(10000,300000,30)
a

array([ 10000.,  20000.,  30000.,  40000.,  50000.,  60000.,  70000.,
        80000.,  90000., 100000., 110000., 120000., 130000., 140000.,
       150000., 160000., 170000., 180000., 190000., 200000., 210000.,
       220000., 230000., 240000., 250000., 260000., 270000., 280000.,
       290000., 300000.])

In [56]:
b = a.sum()
b

4650000.0

In [57]:
c = np.logspace(0,29,30,base=2) / 100
sum = c.sum()
sum

10737418.23

In [58]:
sum - b

6087418.23

#  全0数列

创建指定大小的数组，数组元素以 0 来填充

```python
numpy.zeros(shape, dtype = float, order = 'C')
```

参数说明   

| 序号 | 参数 | 描述说明 |
| :--- | :--- | :--- |
| 1      | shape| 数组形状  |
| 2   | dtype | 数据类型，可选     |

In [59]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros(5, dtype='int')

array([0, 0, 0, 0, 0])

In [61]:
np.zeros((3,2), dtype='int')

array([[0, 0],
       [0, 0],
       [0, 0]])

In [62]:
np.zeros((3,2,2), dtype='int')

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [63]:
a = np.array([[1,2,3],(4,5,6)])
b = np.zeros_like(a)
b

array([[0, 0, 0],
       [0, 0, 0]])

In [64]:
a = np.array(([1,2,3],[4,5,6]))
a

array([[1, 2, 3],
       [4, 5, 6]])

# 全1数列

In [65]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [66]:
np.ones((2,3),dtype='int')

array([[1, 1, 1],
       [1, 1, 1]])

In [67]:
np.ones((2,3,3),dtype='int')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [68]:
a = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ]
])

In [69]:
b = np.zeros_like(a)
b

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [70]:
type(b)

numpy.ndarray

# NumPy 数组属性
NumPy 的数组中比较重要 ndarray 对象属性有：

| 属性             | 说明                                        |
| ---------------- | :------------------------------------------ |
| ndarray.ndim     | 秩，即轴的数量或维度的数量                  |
| ndarray.shape    | 数组的维度，对于矩阵，n 行 m 列             |
| ndarray.size     | 数组元素的总个数，相当于 .shape 中 n*m 的值 |
| ndarray.dtype    | ndarray 对象的元素类型                      |
| ndarray.itemsize | ndarray 对象中每个元素的大小，以字节为单位  |


<b>转载[知乎](https://www.zhihu.com/question/64894713)</b>

刚学习numpy，对此查找了一下，给出下面的解释，希望能帮到题主。

1.ndim中的dim是英文dimension维度的缩写。numpy文档中对ndim的属性见下图解释。<img src="https://pica.zhimg.com/50/v2-d9f921131f26de2eb3bab2f6a2fe843f_720w.jpg?source=1940ef5c" data-rawwidth="717" data-rawheight="447" data-original-token="v2-d9f921131f26de2eb3bab2f6a2fe843f" class="origin_image zh-lightbox-thumb" width="717" data-original="https://picx.zhimg.com/v2-d9f921131f26de2eb3bab2f6a2fe843f_r.jpg?source=1940ef5c"/>因此对于一个数组，其shape属性的长度（length）也既是它的ndim.如下图，一个一维数组c，ndim是1，shape的长度也是1<img src="https://pic1.zhimg.com/50/v2-63fe4068aaf3bfa4c8542182cbda2b12_720w.jpg?source=1940ef5c" data-rawwidth="783" data-rawheight="286" data-original-token="v2-63fe4068aaf3bfa4c8542182cbda2b12" class="origin_image zh-lightbox-thumb" width="783" data-original="https://pic1.zhimg.com/v2-63fe4068aaf3bfa4c8542182cbda2b12_r.jpg?source=1940ef5c"/>

在下面这个例子中，数组的ndim为2(它有[两个维度](https://www.zhihu.com/search?q=两个维度&search_source=Entity&hybrid_search_source=Entity&hybrid_search_extra={"sourceType"%3A"answer"%2C"sourceId"%3A228169291})).第一个**维度的长度**为2，也就是有两个子数组,第二个维度的长度为3，也就是每个子数组里有三个元素，shape属性返回的是（2，3）

```sh
[[ 1., 0., 0.],
 [ 0., 1., 2.]] 
```

你也可以这样来理解：

当用数组下标表示的时候，需要用几个数字来表示才能唯一确定这个元素，这个数组就是几维。

例如，一维数组a = [1,2,3,4,5,8],取得一个元素用**a[i]，**只有一层

下面是一个二维数组，ndim为2，shape属性值为（3，3）

```sh
b = 
[
   [1,2,3],
   [4,5,6],
   [7,8,9]
]
取得一个确切的元素，用b[i][j]的格式,数组嵌套了2层，第一层有三个元素，第二层也是三个元素
```

下面是一个三维数组，ndim为3，shape属性值为（2，2，3）

```sh
c = 
[
    [
        [1,2,3],
        [4,5,6]
    ],
    [
       [7,8,9],
       [10,11,12]
    ]
]
取得一个确切的元素，
用b[i][j][k]的格式,数组嵌套了3层，第一层有2个元素，第二层也是2个元素,第三层有三个元素
```



我根据博主的讲解我总结了一下：

1. `ndim`主要是看内嵌了多少个`[]`,一般都习惯是列表，而不是用元组，故只需观察内嵌的中括号个数就是`ndim`的数量
2. `shape`主要是逐层分解中括号，去掉一层在看内部有多少个元素。

In [71]:
a = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
])

In [72]:
a.ndim # 3

3

In [73]:
a.shape # 2，3，3

(2, 3, 3)

In [74]:
a.size # 2*3*3

18

In [75]:
a.dtype

dtype('int64')

In [76]:
a.itemsize

8

#### 调整维度 reshape
返回调整维度后的副本，而不改变原 ndarray。

In [77]:
a = np.arange(1,20+1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [78]:
b = a.reshape((4,5))

In [79]:
print('a:',a)
print('b:',b)

a: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
b: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


### 调整维度 resize
`numpy.resize(a, new_shape)`
如果新数组大于原始数组，则新数组将填充a的重复副本。
> 请注意，此行为与a.resize(new_shape)不同，后者用零而不是重复的a填充。

In [80]:
a = np.array([
    [1,2],
    [3,4]
])

In [81]:
b = np.resize(a,(2,3))
b

array([[1, 2, 3],
       [4, 1, 2]])

In [82]:
a

array([[1, 2],
       [3, 4]])

☝️上面的会先展开，然后在填充

In [83]:
a.resize((5,10),refcheck = False) # 用零而不是重复的a填充。
a

array([[1, 2, 3, 4, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

#### 方法astype()
numpy数据类型转换，调用astype返回数据类型修改后的数据，但是源数据的类型不会变

In [84]:
c = a.astype('float64')
c.dtype

dtype('float64')

In [85]:
a.dtype

dtype('int64')

### ndarray.itemsize
以字节的形式返回数组中每一个元素的大小。

例如，一个元素类型为 float64 的数组 itemsize 属性值为 8(float64 占用 64 个 bits，每个字节长度为 8，所以 64/8，占用 8 个字节）

In [86]:
a = np.array([1.1,2.2,3.3])
print('dtype:',a.dtype,' itemsize:',a.itemsize)

b = np.array([1,2,3,4,5]).astype('str_')
print('dtype:',b.dtype,' itemsize:',b.itemsize)

dtype: float64  itemsize: 8
dtype: <U21  itemsize: 84


# 数据类型

| 名称           | 描述                                                         | 名称          | 描述                                                         |
| -------------- | :----------------------------------------------------------- | ------------- | :----------------------------------------------------------- |
| bool_          | 布尔型数据类型（True 或者 False）                            | float_        | float64 类型的简写                                           |
| int_           | 默认的整数类型（类似于 C 语言中的 long，int32 或 int64）     | float16/32/64 | 半精度浮点数:1 个符号位，5 个指数位，10个尾数位<br/>单精度浮点数:1 个符号位，8 个指数位，23个尾数位<br/>双精度浮点数,包括：1 个符号位，11 个指数位，52个尾数位 |
| intc           | 和 C 语言的 int 类型一样，一般是 int32 或 int 64             | complex_      | 复数类型，与 complex128 类型相同                             |
| intp           | 用于索引的整数类型（类似于 C 的 ssize_t，通常为 int32 或 int64） | complex64/128 | 复数，表示双 32 位浮点数（实数部分和虚数部分）<br/>复数，表示双 64 位浮点数（实数部分和虚数部分） |
| int8/16/32/64  | 代表与1字节相同的8位整数<br/>代表与2字节相同的16位整数<br/>代表与4字节相同的32位整数<br/>代表与8字节相同的64位整数 | str_          | 表示字符串类型                                               |
| uint8/16/32/64 | 代表1字节（8位）无符号整数<br/>代表与2字节相同的16位整数<br/>代表与4字节相同的32位整数<br/>代表与8字节相同的64位整数 | string_       | 表示字节串类型,也就是bytes类型                               |

