# Numpy ndarray对象

- `numpy`定义了一个n维数组对象，简称`ndarray`对象，它是一个一系列`相同`类型元素组成的数组集合。数组中的每个元素都占有大小相同的内存块。
- `ndarray`对象采用了数组的`索引机制`，将数组中的每个元素映射到内存块上，并且按照一定的布局对内存块进行排列。



In [1]:
import numpy as np

# numpy创建数组

```python
numpy.array(object, dtype = None, copy = True, Order = None, subok = False, ndmin = 0)
```

参数：

| 序号 | 参数   | 描述说明                                                     |
| ---- | ------ | :----------------------------------------------------------- |
| 1    | object | 表示一个数组序列                                             |
| 2    | dtype  | 可选参数，通过它可以改变数组的数据类型                       |
| 3    | copy   | 可选，当数据源是ndarray是表示数组能否被复制，默认是True                  |
| 4    | Order  | 可选，以哪种内存布局创建数组，有3个可选值，分别是C（行序列）/F（列序列）/A（默认） |
| 5    | ndmin  | 可选，用于指定数组维数                                       |
| 6    | subok  | 可选，类型为bool，默认为False。为True时，使用object的内部数据类型；为False时，使用object数组的数据类型。 |



In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [4]:
np.array((1,2,3,4,5)) # 元组

array([1, 2, 3, 4, 5])

In [5]:
type(np.array((1,2,3,4,5)))

numpy.ndarray

In [6]:
a = np.array([1,2,3,4,5])

b = np.array(a)

b

array([1, 2, 3, 4, 5])

In [7]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.array([i**2 for i in range(10)]) # 里面是列表

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
# 创建10以内的偶数的数组
np.array([i for i in range(10) if i%2 == 0])

array([0, 2, 4, 6, 8])

In [10]:
# 第二种做法
np.array(range(0,11,2))

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.array([1,1.4,'5'])

array(['1', '1.4', '5'], dtype='<U32')

In [12]:
# 二维数组(可以嵌套，列表元组都可以)
np.array([
    [1,'b',3],
    ('1','b','3')
])

array([['1', 'b', '3'],
       ['1', 'b', '3']], dtype='<U21')

In [18]:
arr = np.array([
    [1,2,3],
    ('a','b','c')
])

In [19]:
arr

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U21')