# Numpy ndarray对象

- `numpy`定义了一个n维数组对象，简称`ndarray`对象，它是一个一系列`相同`类型元素组成的数组集合。数组中的每个元素都占有大小相同的内存块。
- `ndarray`对象采用了数组的`索引机制`，将数组中的每个元素映射到内存块上，并且按照一定的布局对内存块进行排列。



In [1]:
import numpy as np

# numpy创建数组

```python
numpy.array(object, dtype = None, copy = True, Order = None, subok = False, ndmin = 0)
```

参数：

| 序号 | 参数   | 描述说明                                                     |
| ---- | ------ | :----------------------------------------------------------- |
| 1    | object | 表示一个数组序列                                             |
| 2    | dtype  | 可选参数，通过它可以改变数组的数据类型                       |
| 3    | copy   | 可选，当数据源是ndarray是表示数组能否被复制，默认是True                  |
| 4    | Order  | 可选，以哪种内存布局创建数组，有3个可选值，分别是C（行序列）/F（列序列）/A（默认） |
| 5    | ndmin  | 可选，用于指定数组维数                                       |
| 6    | subok  | 可选，类型为bool，默认为False。为True时，使用object的内部数据类型；为False时，使用object数组的数据类型。 |



In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [4]:
np.array((1,2,3,4,5)) # 元组

array([1, 2, 3, 4, 5])

In [5]:
type(np.array((1,2,3,4,5)))

numpy.ndarray

In [6]:
a = np.array([1,2,3,4,5])

b = np.array(a)

b

array([1, 2, 3, 4, 5])

In [7]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.array([i**2 for i in range(10)]) # 里面是列表

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
# 创建10以内的偶数的数组
np.array([i for i in range(10) if i%2 == 0])

array([0, 2, 4, 6, 8])

In [10]:
# 第二种做法
np.array(range(0,11,2))

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.array([1,1.4,'5'])

array(['1', '1.4', '5'], dtype='<U32')

In [12]:
# 二维数组(可以嵌套，列表元组都可以)
np.array([
    [1,'b',3],
    ('1','b','3')
])

array([['1', 'b', '3'],
       ['1', 'b', '3']], dtype='<U21')

In [15]:
# 注意嵌套序列数量不一会怎么样
ar4 = np.array([[1,2,3],[1,2,3]]) 

In [16]:
ar4

array([[1, 2, 3],
       [1, 2, 3]])

In [17]:
ar4.shape

(2, 3)

 1. 设置dtype参数，默认自动识别

In [18]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [19]:
a_dtype = np.array(a, dtype = 'float')
a_dtype

array([1., 2., 3., 4., 5.])

## 思考如何将浮点型的数据，设置为整形，会是什么情况？

In [20]:
np.array([1.1,2.2,3,1.2], dtype = 'int')

array([1, 2, 3, 1])

 2.设置copy参数,默认为True

In [21]:
a = np.array([1,2,3,4,5])
b = np.array(a)

In [25]:
print('a:',id(a),'b:',id(b))

a: 4884481680 b: 4884480816


In [26]:
a = np.array([1,2,3,4,5])
# 定义b，当设置copy参数为Fasle时，不会创建副本，
# 两个变量会指向相同的内容地址，没有创建新的对象
b = np.array(a, copy=False)
# 输出a和b的id
print('a:', id(a), '  b:', id(b))
print('以上看出a和b的内存地址')
# 由于a和b指向的是相同的内存地址，因此当修改b的元素时，a会发生变化
b[0] = 10
print('a:',a,'  b:',b)

a: 4887070256   b: 4887070256
以上看出a和b的内存地址
a: [10  2  3  4  5]   b: [10  2  3  4  5]


当默认为True时，表明是独立的复制，而不是引用；
为False时，表明是引用

3. ndmin 用于指定数组的维度

In [27]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [28]:
b = np.array(a, ndmin = 2)
b

array([[1, 2, 3]])

4.subok参数，类型为bool值，默认False。为True，使用object的内部数据类型；False：使用object数组的数据类型。

In [29]:
# 创建一个矩阵
a = np.mat([1,2,3,4])
# 输出为矩阵类型
print(type(a))

#既要复制一份副本，又要保持原类型
at = np.array(a,subok=True)
af = np.array(a)  # 默认为False
print('at,subok为True:',type(at))
print('af,subok为False:',type(af))
print(id(at),id(a))


<class 'numpy.matrix'>
at,subok为True: <class 'numpy.matrix'>
af,subok为False: <class 'numpy.ndarray'>
4878398912 4878398656


In [30]:
a = np.array([1,2,3,4])
c = a.copy() # copy使用的多一点
print(id(a),id(c))

4883697712 4885630000



# arange()生成区间数组
根据 start 与 stop 指定的范围以及 step 设定的步长，生成一个 ndarray。

```python
numpy.arange(start, stop, step, dtype)
```
参数说明   

| 序号 | 参数 | 描述说明 |
| :--- | :--- | :--- |
| 1      | start| 起始值，默认为0   |
| 2   | stop | 终止值（不包含）        |
| 3      | step | 步长，默认为1        |
| 4      | dtype |  返回ndarray的数据类型，如果没有提供，则会使用输入数据的类型。     |

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(3.1)

array([0., 1., 2., 3.])

In [34]:
range(3)

range(0, 3)

In [35]:
np.arange(4,dtype = 'float')

array([0., 1., 2., 3.])

In [36]:
np.arange(10,100,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [37]:
np.arange(100000) # 只打印边边角角

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [38]:
np.arange(20,step = 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [40]:
arr = np.arange(200+1,step = 3)

In [42]:
len(arr)

67

## 如何防止 float 不精确影响numpy.arange
> <font color=red>注意：ceil((stop - start)/step)确定项目数，小浮点不精确(stop = .400000001)可以向列表中添加意外值。</font>
#### 想得到一个长度为3的、从0.1开始的、间隔为0.1的数组，想当然地如下coding，结果意料之外：

In [44]:
np.arange(0.1,0.5,0.1)

array([0.1, 0.2, 0.3, 0.4])