# 切片和索引

ndarray对象的内容可以通过索引或切片来访问和修改，与 Python 中 list 的切片操作一样。

ndarray 数组可以基于 0 - n 的下标进行索引


>区别在于：<font color='red'>数组切片是原始数组视图（这就意味着，如果做任何修改，原始都会跟着更改）。
这也意味着，如果不想更改原始数组，我们需要进行显式的复制，从而得到它的副本（.copy())。</font>

`冒号分隔切片参数 [start:stop:step]`

In [1]:
import numpy as np

## 一维数组

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
b = a[2:7:2] # 从索引2开始到7结束，间隔为2
b

array([2, 4, 6])

冒号 : 的解释：如果只放置一个参数，
- 如 [2]，将返回与该索引相对应的单个元素。
- 如果为 [2:]，表示从该索引开始以后的所有项都将被提取。
- 如果使用了两个参数，如 [2:7]，那么则提取两个索引(不包括停止索引)之间的项。

In [4]:
a[2:8:2]

array([2, 4, 6])

In [5]:
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a[:7] # 不包含末尾元素

array([0, 1, 2, 3, 4, 5, 6])

In [7]:
a = np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [8]:
a[4]

9

In [9]:
a[::-1] # 反着取值

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [10]:
a[:-2:1] # 第一个到倒数第二个 倒数第二个不取

array([ 1,  3,  5,  7,  9, 11, 13, 15])

## 为什么切片和区间会忽略最后一个元素
计算机科学家edsger w.dijkstra(艾兹格·W·迪科斯彻)，delattr这一风格的解释应该是比较好的：
- 当只有最后一个位置信息时，我们可以快速看出切片和区间里有几个元素：range(3)和my_list[:3]
- 当起始位置信息都可见时，我们可以快速计算出切片和区间的长度，用有一个数减去第一个下表(stop-start)即可
- 这样做也让我们可以利用任意一个下标把序列分割成不重叠的两部分，只要写成my_list[:x]和my_list[x:]就可以了。

## 二维数组
### 同样使用上述索引提取方法

In [11]:
a = np.arange(1,20+1).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [12]:
a.ndim # 2

2

In [13]:
a.shape # (4,5)

(4, 5)

In [14]:
a[0]

array([1, 2, 3, 4, 5])

In [15]:
a[1]

array([ 6,  7,  8,  9, 10])

In [16]:
a[2]

array([11, 12, 13, 14, 15])

In [17]:
a[2][2] # 13

13

In [18]:
a[2:] # 从第三行开始以后全都要

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

>注意：切片还可以使用省略号“…”，如果在行位置使用省略号，那么返回值将包含所有行元素，反之，则包含所有列元素。

In [19]:
a[...,2] # 全体第三列元素

array([ 3,  8, 13, 18])

In [20]:
a[...,2:] # 从第三列开始截取 后面的都要

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [21]:
a[2][2] == a[2,2]

True

In [22]:
a[...][2] # 取所有的行 然后取第三项

array([11, 12, 13, 14, 15])

第一个`:,`代表第一个维度，`,`后面的表示取第二维的所有第几位数据

In [23]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [24]:
a[:,2] # 取第三列数据

array([ 3,  8, 13, 18])

In [25]:
a[...]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
a[...,2]

array([ 3,  8, 13, 18])

In [27]:
a[...,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [28]:
a[...,2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]])

In [29]:
a[...,:2] # 第三列之前的全部数据

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [30]:
a[...,:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

# 总结
 - 即高维数组是以`，`来划分维度，逗号前是一个维度，逗号后是另外一个维度，互不干涉
 - `：`冒号是用来进行操作的，这里和一位数组类似。

# 索引的高级操作
在 NumPy 中还可以使用高级索引方式，比如整数数组索引、布尔索引，以下将对两种种索引方式做详细介绍。


### 1. 整数数组索引

In [31]:
x = np.array([
    [1,2],
    [3,4],
    [5,6]
])